config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  get 'payments/index'
  get 'get_items' => "payments#ws_get_items"

  resources :products
  resources :payments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @payment = Payment.new
  end


  def create
    begin


    rescue Exception => e
      puts e
    end
  end

  def index
  end

  def ws_get_items

    # require 'mercadopago.rb'

    begin
      items = params[:items].split(',')

      _items = Product.where(id: items)
      items_to_payment = []

      _items.each do |item|
        items_to_payment << {
          "title": item.name,
          "quantity": 1,
          "unit_price": item.price,
          "currency_id": "MXN"
        }
      end


      $mp = MercadoPago.new('7339671726493538', 'DQhRNolluJxFzI2Y29m208wrCU6Fnenj')
      preference_data = {
            "items": items_to_payment
        }
      preference = $mp.create_preference(preference_data)
      preference = []


      render :json => {:success => 1, count: _items.size, items: _items, payment: preference}
    rescue Exception => e
      render :json => {:success => 0, :message => e.message}
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :image_link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MercadoPago</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/index.html.erb
<h1>Payments#index</h1>
<p>Find me in app/views/payments/index.html.erb</p>

app/views/payments/new.html.erb
<%= form_with(model: @payment, local: true) do |form| %>


  <div class="field">
    <%= form.label :'Nombre de la persona' %>
    <%= form.text_field :name %>
  </div>

  <div id="items">

  </div>

  <div class="field">
    <%= form.label :items %>
    <%= form.text_field :items %>
  </div>

  <div class="field">
    <%= form.label :card_number %>
    <%= form.text_area :card_number, id: :card_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <div id="template_for_items" style="display:none">
    <div class="item">
      <img src="%IMAGE%" width="80"/>
      <div class="title">%NAME%</div> - <div class="price">$ %PRICE%</div>
    </div>
  </div>

  <script type="text/javascript">
    var items = JSON.parse(localStorage.getItem('items_to_payment'));
    
    $.ajax({
      url: "<%= get_items_path %>",
      data: "items=" + items,
      dataType: "json",
      success: function (data) {
        console.log(data.items)
        $.each(data.items,function(i,item){
          html = $("#template_for_items").html();

          regex = new RegExp("%NAME%", 'g');
          html = html.replace(regex, String(item.name));

          regex = new RegExp("%PRICE%", 'g');
          html = html.replace(regex, String(item.price));

          regex = new RegExp("%IMAGE%", 'g');
          html = html.replace(regex, String(item.image_link));

          $("#items").append(html)
        });
        console.log(data)
      },
      failure: function () {
        alert("error al cargar los items a pagar")
      }
    });
  </script>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :image_link %>
    <%= form.text_area :image_link, id: :product_image_link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Image link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><img src="<%= product.image_link %>" width="100"/></td>
        <td>Seleccionar para comprar <input type="checkbox" onclick="addItem(this,<%= product.id %>)"/></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button onclick="goToPayemntPage();"> Pagar Articulos</button>
<br>
<%= link_to 'New Product', new_product_path %>

<script type="text/javascript">
  // Guardar variable en las cache del navegador
  items = [];

  function goToPayemntPage(){
    if (items.length > 0) {

      localStorage.setItem("items_to_payment", JSON.stringify(items));
      window.location.href = '/payments/new'
    }else{
      alert("Seleccione por lo menos un articulo")
    }

  }

  function addItem(checkbox,item){

    if (checkbox.checked) {
      if (items.length > 0) {
          for (var i = 0; i < items.length; i++) {
            if (items[i] == item){
              return;
            }
          }
      }
      items.push(item);

    }else{
      tmp_array = []
      for (var i = 0; i < items.length; i++) {
        if (items[i] != item){
          tmp_array.push(items[i]);
        }
      }

      items = tmp_array;
    }


  }
</script>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Image link:</strong>
  <%= @product.image_link %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>